import Head from 'next/head'
import Image from 'next/image'
import { Heading, Link } from '@chakra-ui/layout';
import Hero from './components/Hero';
import Features from './components/Features';
import Subnav from './components/Subnav';

export default function Landing() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
<Subnav/>

      </main>

    </div>
  )
}
